# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wooaham' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SwipeCellKit'
  pod 'NMapsMap'
  pod 'Firebase/Analytics' 
  pod 'Firebase/Messaging'

  # Pods for Wooaham

end
